# Generated by Django 5.2 on 2025-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
