# Generated by Django 5.2 on 2025-06-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operation_number',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
