# Generated by Django 5.2 on 2025-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_operation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guid',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='operation_number',
            field=models.BigIntegerField(),
        ),
    ]
