# Generated by Django 5.2 on 2025-06-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_guid_alter_order_operation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
