# Generated by Django 5.2 on 2025-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_guid_alter_order_operation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
