# Generated by Django 5.2 on 2025-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_Code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
