# Generated by Django 5.2 on 2025-06-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Unkown', max_length=255,unique=True),
            preserve_default=False,
        ),
    ]
