# Generated by Django 5.2 on 2025-05-31 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('how_to_play', models.TextField()),
                ('time', models.SmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='exercises/videos/')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_muscles', to='programs.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle', to='programs.muscle')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('advice_en', models.TextField(blank=True, null=True)),
                ('advice_ar', models.TextField(blank=True, null=True)),
                ('days', models.IntegerField()),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('daily_time', models.CharField(max_length=255)),
                ('kalories', models.IntegerField()),
                ('plan_goal_en', models.CharField(max_length=50)),
                ('plan_goal_ar', models.CharField(max_length=50)),
                ('weeks', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plans/images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_plan', to='programs.sport')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps_en', models.CharField(max_length=255)),
                ('reps_ar', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_detail', to='programs.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='programs.plan')),
            ],
            options={
                'unique_together': {('plan', 'exercise', 'week', 'day')},
            },
        ),
    ]
