# Generated by Django 5.2 on 2025-05-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_plansubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='coach',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='user',
            new_name='owner',
        ),
    ]
