# Generated by Django 5.2 on 2025-05-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_rename_coach_exercise_owner_rename_user_plan_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansubscription',
            name='plan_type',
        ),
    ]
