# Generated by Django 5.2 on 2025-05-31 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_remove_plansubscription_plan_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('fitness&nutrition', 'Fitness&Nutrition')], max_length=255)),
                ('question_en', models.TextField()),
                ('question_ar', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('fitness&nutrition', 'Fitness&Nutrition')], max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_plan_requests', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_en', models.TextField()),
                ('answer_ar', models.TextField()),
                ('plan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='programs.planrequest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.coachquestion')),
            ],
            options={
                'unique_together': {('plan_request', 'question')},
            },
        ),
    ]
