# Generated by Django 5.2 on 2025-06-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_coachquestion_planrequest_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='how_to_play',
            new_name='how_to_play_ar',
        ),
        migrations.AddField(
            model_name='exercise',
            name='how_to_play_en',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
