# Generated by Django 5.2 on 2025-06-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_rename_how_to_play_exercise_how_to_play_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name_ar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
    ]
