# Generated by Django 5.2 on 2025-06-05 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_exercise_name_ar_alter_exercise_name_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('meal_number', models.PositiveSmallIntegerField()),
                ('meal_name_en', models.CharField(max_length=100)),
                ('meal_name_ar', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('quantity', models.SmallIntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='programs.mealdetail')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('advice_en', models.TextField(blank=True, null=True)),
                ('advice_ar', models.TextField(blank=True, null=True)),
                ('weeks', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='nutrition/images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mealdetail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='programs.nutritionplan'),
        ),
        migrations.AlterUniqueTogether(
            name='mealdetail',
            unique_together={('plan', 'week', 'day', 'meal_number')},
        ),
    ]
