# Generated by Django 5.2 on 2025-06-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_mealdetail_fooditem_nutritionplan_mealdetail_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='plan_pay_level',
            field=models.CharField(choices=[('free', 'free'), ('gold', 'gold'), ('platinum', 'platinum')], default='free', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_pay_level',
            field=models.CharField(choices=[('free', 'free'), ('gold', 'gold'), ('platinum', 'platinum')], default='free', max_length=100),
            preserve_default=False,
        ),
    ]
