# Generated by Django 5.2 on 2025-06-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_nutritionplan_plan_pay_level_plan_plan_pay_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer_ar',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer_en',
        ),
    ]
