# Generated by Django 5.2 on 2025-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_rename_answer_ar_useranswer_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisedetail',
            old_name='day',
            new_name='day_number',
        ),
        migrations.RenameField(
            model_name='exercisedetail',
            old_name='week',
            new_name='week_number',
        ),
        migrations.AlterUniqueTogether(
            name='exercisedetail',
            unique_together={('plan', 'exercise', 'week_number', 'day_number')},
        ),
        migrations.AddField(
            model_name='exercisedetail',
            name='day_name',
            field=models.CharField(default='first', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisedetail',
            name='week_name',
            field=models.CharField(default='first', max_length=255),
            preserve_default=False,
        ),
    ]
