# Generated by Django 5.2 on 2025-06-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_rename_day_exercisedetail_day_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisedetail',
            name='rest_between_exercises',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisedetail',
            name='rest_between_sets',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
    ]
