# Generated by Django 5.2 on 2025-06-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_exercisedetail_rest_between_exercises_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('rest_between_exercises', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exercisedetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='exercisedetail',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.exercise'),
        ),
        migrations.AddField(
            model_name='exercisedetail',
            name='day',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.day'),
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_weeks', to='programs.plan')),
            ],
            options={
                'unique_together': {('plan', 'number')},
            },
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_days', to='programs.week'),
        ),
        migrations.RemoveField(
            model_name='exercisedetail',
            name='day_name',
        ),
        migrations.RemoveField(
            model_name='exercisedetail',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='exercisedetail',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='exercisedetail',
            name='rest_between_exercises',
        ),
        migrations.RemoveField(
            model_name='exercisedetail',
            name='week_name',
        ),
        migrations.RemoveField(
            model_name='exercisedetail',
            name='week_number',
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('week', 'number')},
        ),
    ]
