# Generated by Django 5.2 on 2025-06-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_day_alter_exercisedetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisedetail',
            name='exercise_type',
            field=models.CharField(choices=[('warm_up', 'warm_up'), ('main_exercise', 'main_exercise'), ('stretching', 'stretching')], default='main_exercise', max_length=255),
        ),
    ]
